# Build libzkp dependency
FROM scrolltech/go-rust-builder:go-1.19-rust-nightly-2022-12-10 as chef
WORKDIR app

FROM chef as planner
COPY ./l2geth/rollup/circuitcapacitychecker/libzkp/ .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef as zkp-builder
COPY ./l2geth/rollup/circuitcapacitychecker/libzkp/rust-toolchain ./
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

COPY ./l2geth/rollup/circuitcapacitychecker/libzkp .
RUN cargo build --release
RUN find ./ | grep libzktrie.so | xargs -I{} cp {} /app/target/release/

# Build Geth in a stock Go builder container
FROM scrolltech/go-rust-builder:go-1.19-rust-nightly-2022-12-10 as builder

ADD . /scroll
COPY --from=zkp-builder /app/target/release/libzkp.so /usr/local/lib/
COPY --from=zkp-builder /app/target/release/libzktrie.so /usr/local/lib/
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
RUN cd /scroll/rollup && make rollup_bins
RUN cd ../database && make db_cli

# Pull Geth into a second stage deploy alpine container
FROM ubuntu:20.04

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends ca-certificates

COPY --from=builder /scroll/rollup/build/bin/event_watcher /usr/local/bin/
COPY --from=builder /scroll/rollup/build/bin/gas_oracle /usr/local/bin/
COPY --from=builder /scroll/rollup/build/bin/rollup_relayer /usr/local/bin/
COPY --from=builder /scroll/database/build/bin/rollup_relayer /usr/local/bin/
COPY --from=zkp-builder /app/target/release/libzkp.so /usr/local/lib/
COPY --from=zkp-builder /app/target/release/libzktrie.so /usr/local/lib/
COPY run_rollup_relayer.sh /usr/local/bin
RUN chmod 755 /usr/local/bin/run_rollup_relayer.sh
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/

ENTRYPOINT []